Apply a style on loading RasterImageLayer if the style is saved as si…
openjump-gis/openjump pull request #135
Opened 2024-08-20 08:02 UTC by ma15569

Apply a style on loading RasterImageLayer if the style is saved as sidecar SLD file . Currently OpenJUMP can read/write symbology only for monoband raster files.

2024-08-20 08:03 UTC, ma15569 commented
Hi Ede, I prefer to close the previous pull request and open another one.

2024-08-20 09:17 UTC, edeso requested changes

2024-08-20 09:17 UTC, edeso commented on src/org/openjump/core/rasterimage/AddRasterImageLayerWizard.java
> +            // "sld");
please remove the commented code. it's not helpful.

apart from that. no objections. nice indention :)

2024-08-26 10:26 UTC, edeso commented
something happened again to the indention :). see 
![Screenshot 2024-08-26 122413](https://github.com/user-attachments/assets/8b21615b-9ba5-4a42-bb5d-bb4a4feccdf7)

i'll fix that locally. i'll readd you comment on the purpose of the code, as i merely pointed out the uselessness of the comment "wrong way" to determine the file name.

2024-08-26 10:34 UTC, edeso approved these changes

2024-08-26 10:36 UTC, merged