Logging upgrade part 1: Consistently use the internal workbench.Logger
openjump-gis/openjump pull request #50
Opened 2022-04-29 09:36 UTC by Neutius

This is the first step towards resolving https://github.com/openjump-gis/openjump/issues/49

Only the workbench.Logger class should be aware of the logging implementation used (currently Log4j 1, will be upgraded to Log4j 2 soon).

There were 6 classes directly using the Log4j 1 logging implementation. Those classes now use the internal workbench.Logger class.

I also expanded the .gitignore for IntelliJ IDE config files, to prevent accidentally committing those.

2022-05-04 12:07 UTC, edeso commented on src/com/vividsolutions/jump/workbench/ui/WorkbenchFrame.java
> +        Logger.info(message);
please keep this, it points out from where the log() method call came

you can point log(String) to log(String,Class) though

2022-05-04 12:57 UTC, edeso requested changes
can you rework `com.vividsolutions.jump.workbench.Logger` to contain an exposable Level class?

2022-05-04 12:57 UTC, edeso commented on src/com/vividsolutions/jump/workbench/ui/WorkbenchFrame.java
> +        Logger.info(message);
same here, pls keep the stack

2022-05-04 12:57 UTC, edeso commented on src/com/vividsolutions/jump/workbench/ui/WorkbenchFrame.java
> +        Logger.info(message, t);
same here. let's expose Log-Levels via static Members of class Logger to get rid of the `org.apache.log4j.Level` import instead.

2022-05-05 09:52 UTC, edeso commented
i quickly threw something together to abstract the Log Levels
 https://github.com/openjump-gis/openjump/commit/4d40782dbd4986bf9497f9feaa4a6d5763e33ad5

feel free to reuse or ignore :)

2022-05-05 11:42 UTC, Neutius commented
@edeso I found your commit quite useful, but I did make a few different decisions.

I used an enum type, since an enum does all that we need out of the box, so we don't need to compare String values ourselves.

For the enum type name, I chose LogLevel over "Level", both to prevent namespace conflict with log4j Level, and to make the intended purpose more explicit. Within a logging framework "Level" is specific enough, but within in a broader application context "Level" could mean dozens of things.

2022-05-05 11:59 UTC, edeso commented
No problem. as long as it works! looking forward to your Log4J 2.x port :)

2022-05-06 12:34 UTC, edeso approved these changes
looks good

2022-05-06 12:34 UTC, merged